#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : virglrenderer
Version  : 0.10.4
Release  : 5
URL      : https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/0.10.4/virglrenderer-0.10.4.tar.gz
Source0  : https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/0.10.4/virglrenderer-0.10.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: virglrenderer-bin = %{version}-%{release}
Requires: virglrenderer-filemap = %{version}-%{release}
Requires: virglrenderer-lib = %{version}-%{release}
Requires: virglrenderer-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : libepoxy-dev
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(libdrm)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
`Virglrenderer <https://virgil3d.github.io/>`_ - The VirGL virtual OpenGL renderer
==================================================================================

%package bin
Summary: bin components for the virglrenderer package.
Group: Binaries
Requires: virglrenderer-license = %{version}-%{release}
Requires: virglrenderer-filemap = %{version}-%{release}

%description bin
bin components for the virglrenderer package.


%package dev
Summary: dev components for the virglrenderer package.
Group: Development
Requires: virglrenderer-lib = %{version}-%{release}
Requires: virglrenderer-bin = %{version}-%{release}
Provides: virglrenderer-devel = %{version}-%{release}
Requires: virglrenderer = %{version}-%{release}

%description dev
dev components for the virglrenderer package.


%package filemap
Summary: filemap components for the virglrenderer package.
Group: Default

%description filemap
filemap components for the virglrenderer package.


%package lib
Summary: lib components for the virglrenderer package.
Group: Libraries
Requires: virglrenderer-license = %{version}-%{release}
Requires: virglrenderer-filemap = %{version}-%{release}

%description lib
lib components for the virglrenderer package.


%package license
Summary: license components for the virglrenderer package.
Group: Default

%description license
license components for the virglrenderer package.


%prep
%setup -q -n virglrenderer-0.10.4
cd %{_builddir}/virglrenderer-0.10.4
pushd ..
cp -a virglrenderer-0.10.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672853630
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/virglrenderer
cp %{_builddir}/virglrenderer-%{version}/COPYING %{buildroot}/usr/share/package-licenses/virglrenderer/a4924561121fd43cb97468ba0ecce6571b664b29 || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/virgl_test_server
/usr/share/clear/optimized-elf/bin*

%files dev
%defattr(-,root,root,-)
/usr/include/virgl/virglrenderer.h
/usr/lib64/glibc-hwcaps/x86-64-v3/libvirglrenderer.so
/usr/lib64/libvirglrenderer.so
/usr/lib64/pkgconfig/virglrenderer.pc

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-virglrenderer

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libvirglrenderer.so.1
/usr/lib64/glibc-hwcaps/x86-64-v3/libvirglrenderer.so.1.7.7
/usr/lib64/libvirglrenderer.so.1
/usr/lib64/libvirglrenderer.so.1.7.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/virglrenderer/a4924561121fd43cb97468ba0ecce6571b664b29
